# Generated by Django 4.1.7 on 2023-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'P'), ('FAILED', 'F')], default='FAILED', max_length=6),
        ),
    ]
