# Generated by Django 4.1.7 on 2023-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Vise', 'VS'), ('Mastercard', 'MC')], max_length=10),
        ),
    ]
